# file: aws_ec2_instance.yml
---

- name: Configure Container Instances
  hosts: tag_Name_container
  become: yes
  remote_user: "ec2-user"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  roles:
    - { role: container.workshop }


#############################################################
#  USAGE
#############################################################

# Using ec2.py to query AWS for your instance by AWS Tags
#
# ansible-playbook -i inventory 2_aws_ec2.yml
