---

#---------------------------------------------------
#  Subscription Manager
#---------------------------------------------------
- name: disable all amz rhel repos
  command: /usr/bin/yum-config-manager --disable *
  tags:
    - rhel

- name: disable amz yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/amazon-id.conf regexp='^enabled' line='enabled = 0' state=present
  tags:
    - rhel

- name: disable rhui-lb yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/rhui-lb.conf regexp='^enabled' line='enabled = 0' state=present
  tags:
    - rhel

- name: enable product-id yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/product-id.conf regexp='^enabled' line='enabled = 1' state=present
  tags:
    - rhel

- name: enable sub manager yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/subscription-manager.conf regexp='^enabled' line='enabled = 1' state=present
  tags:
    - rhel

- name: add subscription DNS to etc hosts (1)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.44   xmlrpc.rhn.redhat.com'
  tags:
    - rhel

- name: add subscription DNS to etc hosts (2) 
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='23.204.148.218   content-xmlrpc.rhn.redhat.com'
  tags:
    - rhel

- name: add subscription DNS to etc hosts (3)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.49   subscription.rhn.redhat.com'
  tags:
    - rhel

- name: add RH docker registry to etc hosts (4)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.63   registry.access.redhat.com'
  tags:
    - rhel

- name: add jboss.org mvn repository to etc hosts (5)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.33   repository.jboss.org'
  tags:
    - rhel

- name: subscribe RHN
  redhat_subscription: state=present username='{{ username }}' password='{{ password }}' autosubscribe=true pool='{{ pool_id }}'
  tags:
    - rhel

- name: disable all repos by default
  shell: subscription-manager repos --disable="*"
  tags:
    - rhel

- name: Enable the requisite rhel7 repos
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-server-rhscl-7-rpms"
  tags:
    - rhel

- name: Import keys
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
  tags:
    - rhel

